### ISSUE TITLE
ctypes vs swig

### ISSUE THREAD

**Issue by pavanky** [FilipeMaia/afnumpy#1]
There is an (seemingly abandoned) project that uses ctypes to port ArrayFire with similar goals:
https://github.com/arrayfire-community/arrayfire_python

Perhaps you can base your work off of it ?

**Comment by FilipeMaia** [comment]
Yes I saw it, but it's too basic.

**Comment by pavanky** [comment]
Alright. What are the benefits of swig over ctypes ? Just curious.
