### ISSUE TITLE
error: multiarray module missing?

### ISSUE THREAD

**Issue by ZacDiggum** [FilipeMaia/afnumpy#16]
Hi,
I fetched and installed afnumpy via pip. When importing in my script I get an error message:
 File "C:\winpython35\python-3.5.1.amd64\lib\site-packages\afnumpy__init__.py", line 3, in <module>
    from multiarray import ndarray, zeros, where, array, fromstring, arange, empty
ImportError: No module named 'multiarray'
As you can see, I'm on Python 3.5. Arrayfire is v3.3 and works flawless. Also I can see the multiarray.py file in the afnumpy folder. So the file is clearly not missing. Any ideas what's going wrong?
There's another question for when it's working: are arrays interchangeable between afnumpy and the arrayfire python wrapper? That means, are they the same?

Thanks in advance...

Update: When I comment out the line regarding multiarray it won't find the next import module, although all the .py files are right there.

**Comment by FilipeMaia** [comment]
Hi,

I've never tested afnumpy with python 3. I should do it.

afnumpy arrays encapsulate an arrayfire array. You can access the arrayfire array using `array.d_array`, although this is not recommended.

**Comment by ZacDiggum** [comment]
Hi,
I think you are right. It might be a python 3 issue. I tried out arrayfire and afnumpy a couple of months ago with python 2.7 and it worked back then.
My goal is to change my code from pyopencl + reikna to arrayfire + afnumpy. So I'd like to use both in conjunction. Why is that `array.d_array` thing not recommended?
Also, do you have a mailing list or something? I'm sure there might come up some more questions and I don't want to waste space on the issue tracker here. :-)
Well, thanks for the quick reply...

**Comment by ZacDiggum** [comment]
Hi,
today I tried this: in the source zip I changed every print statement to python 3's print(). Now it installs without error. All the byte-compiled files are in 'pycache' folder as should be. Still I get the error message 'no module named multiarray' when importing afnumpy...

update: okay, it seems that relative imports are gone in python 3. one needs to use explicit imports as described here: https://wiki.python.org/moin/PortingPythonToPy3k#relative-imports.
also, there is no numpy.float128 dtype and long changed to int in python 3.
I made some crude changes and now I can import and do basic stuff. Still there is some problem in the indexing module related to https://docs.python.org/3.0/whatsnew/3.0.html section 'Ordering Comparisons'.

**Comment by FilipeMaia** [comment]
I'll try to look at this during the weekend.

**Comment by ZacDiggum** [comment]
I got it to work. I changed
- the print statements to print()
- the imports in every file
- long to int and np.float128 to np.float64 in core/dtypes.py
- the comparisons in indexing.py

Since I'm not sure how to do a pull request, can I send you the files somehow?

**Comment by FilipeMaia** [comment]
It's not hard to create a pull request. Did you make a fork of the repository on github? That would be the first thing to do. Then just push your changes to your own fork and from there you can send the pull request. If you have problems just let me know.
