### ISSUE TITLE
Power function not working ? 

### ISSUE THREAD

**Issue by svvenkatakrishnan** [FilipeMaia/afnumpy#17]
While having a afnumpy array (say xx). The command (-1)**xx, I get the following error : 

TypeError                                 Traceback (most recent call last)
<ipython-input-7-a71d5feef53d> in <module>()
----> 1 zz=(-1)**xx

/usr/local/lib/python2.7/dist-packages/afnumpy/multiarray.pyc in **rpow**(self, other)
    207             s = arrayfire.pow(pu.raw(other), self.astype(type(other)).d_array)
    208         else:
--> 209             s = arrayfire.pow(pu.raw(other), self.d_array)
    210         return ndarray(self.shape, dtype=pu.typemap(s.dtype()), af_array=s)
    211 

/usr/local/lib/python2.7/dist-packages/arrayfire/arith.pyc in pow(lhs, rhs)
    677     - If `lhs` and `rhs` are both af.Array, they must be of same size.
    678     """
--> 679     return _arith_binary_func(lhs, rhs, backend.get().af_pow)
    680 
    681 def pow2(a):

/usr/local/lib/python2.7/dist-packages/arrayfire/arith.pyc in _arith_binary_func(lhs, rhs, c_func)
     40         lty = implicit_dtype(lhs, rhs.type())
     41         other = Array()
---> 42         other.arr = constant_array(lhs, rdims[0], rdims[1], rdims[2], rdims[3], lty)
     43         safe_call(c_func(ct.pointer(out.arr), other.arr, rhs.arr, _bcast_var.get()))
     44 

/usr/local/lib/python2.7/dist-packages/arrayfire/array.py in constant_array(val, d0, d1, d2, d3, dtype)
     50             dtype = ct.c_int(dtype.value)
     51         else:
---> 52             raise TypeError("Invalid dtype")
     53 
     54     out = ct.c_void_p(0)

Is this supported yet ?

**Comment by FilipeMaia** [comment]
Which version of afnumpy and arrayfire was this on?
I don't know what types you used, but the following code works on my machine:

``` python
In [1]: import afnumpy

In [2]: a = afnumpy.ones((3,3))

In [3]: (-1)**a
Out[3]:
array([[-1., -1., -1.],
       [-1., -1., -1.],
       [-1., -1., -1.]])
```

**Comment by svvenkatakrishnan** [comment]
Hi Felipe, 
The afnumpy version is : Version: 1.0b1

Here is another snippet. I wonder if it may have something to do with the array shape. 

Thank you. 

x=afnp.ones((100,1))

## In [72]: b=(-1)**x

TypeError                                 Traceback (most recent call last)
<ipython-input-72-09558736d9a2> in <module>()
----> 1 b=(-1)**x

/usr/local/lib/python2.7/dist-packages/afnumpy/multiarray.pyc in **rpow**(self, other)
    207             s = arrayfire.pow(pu.raw(other), self.astype(type(other)).d_array)
    208         else:
--> 209             s = arrayfire.pow(pu.raw(other), self.d_array)
    210         return ndarray(self.shape, dtype=pu.typemap(s.dtype()), af_array=s)
    211 

/usr/local/lib/python2.7/dist-packages/arrayfire/arith.pyc in pow(lhs, rhs)
    677     - If `lhs` and `rhs` are both af.Array, they must be of same size.
    678     """
--> 679     return _arith_binary_func(lhs, rhs, backend.get().af_pow)
    680 
    681 def pow2(a):

/usr/local/lib/python2.7/dist-packages/arrayfire/arith.pyc in _arith_binary_func(lhs, rhs, c_func)
     40         lty = implicit_dtype(lhs, rhs.type())
     41         other = Array()
---> 42         other.arr = constant_array(lhs, rdims[0], rdims[1], rdims[2], rdims[3], lty)
     43         safe_call(c_func(ct.pointer(out.arr), other.arr, rhs.arr, _bcast_var.get()))
     44 

/usr/local/lib/python2.7/dist-packages/arrayfire/array.py in constant_array(val, d0, d1, d2, d3, dtype)
     50             dtype = ct.c_int(dtype.value)
     51         else:
---> 52             raise TypeError("Invalid dtype")
     53 
     54     out = ct.c_void_p(0)

TypeError: Invalid dtype

**Comment by FilipeMaia** [comment]
Is that from git or pip? Please try again with the github version.

**Comment by svvenkatakrishnan** [comment]
Hi Felipe,

I am still getting the same error after updating to the latest version.

In [1]: import afnumpy as afnp

In [2]: a = afnp.ones((3,3))

## In [3]: (-1)**a

TypeError                                 Traceback (most recent call last)
<ipython-input-3-60aa8554bbcd> in <module>()
----> 1 (-1)**a

/usr/local/lib/python2.7/dist-packages/afnumpy/multiarray.pyc in **rpow**(self, other)
    227             s = arrayfire.pow(pu.raw(other), self.astype(type(other)).d_array)
    228         else:
--> 229             s = arrayfire.pow(pu.raw(other), self.d_array)
    230         a = ndarray(self.shape, dtype=pu.typemap(s.dtype()), af_array=s)
    231         a._eval()

/usr/local/lib/python2.7/dist-packages/arrayfire-3.3.0-py2.7.egg/arrayfire/arith.pyc in pow(lhs, rhs)
    677     - If `lhs` and `rhs` are both af.Array, they must be of same size.
    678     """
--> 679     return _arith_binary_func(lhs, rhs, backend.get().af_pow)
    680 
    681 def pow2(a):

/usr/local/lib/python2.7/dist-packages/arrayfire-3.3.0-py2.7.egg/arrayfire/arith.pyc in _arith_binary_func(lhs, rhs, c_func)
     40         lty = implicit_dtype(lhs, rhs.type())
     41         other = Array()
---> 42         other.arr = constant_array(lhs, rdims[0], rdims[1], rdims[2], rdims[3], lty)
     43         safe_call(c_func(ct.pointer(out.arr), other.arr, rhs.arr, _bcast_var.get()))
     44 

/usr/local/lib/python2.7/dist-packages/arrayfire-3.3.0-py2.7.egg/arrayfire/array.pyc in constant_array(val, d0, d1, d2, d3, dtype)
     50             dtype = ct.c_int(dtype.value)
     51         else:
---> 52             raise TypeError("Invalid dtype")
     53 
     54     out = ct.c_void_p(0)

TypeError: Invalid dtype

**Comment by FilipeMaia** [comment]
What version of arrayfire (not the python bindings but the library itself) are you using?
Please  make sure it's at least 3.3.0. Also you seem to have an old version of arrayfire-python. Please upgrade.

**Comment by svvenkatakrishnan** [comment]
Thank you. It now works. I had an older version.
