### ISSUE TITLE
FFT dtypes

### ISSUE THREAD

**Issue by ZacDiggum** [FilipeMaia/afnumpy#18]
Hi,
I tested fft performance in comparison to vanilla numpy and reikna ( http://reikna.publicfields.net/ ). Reikna does not use clfft but has its own fft implementation. Strange thing: with complex128 dtype, afnumpy is faster than reikna as expected, with complex64 it's not. In fact, times stay the same for both dtypes with afnumpy. Could it be, that afnumpy and arrayfire use complex128 default for ffts? Speed should go up by 4x on my GPU for complex64.

Update: When I use arrayfire-python's ffts directly (not via afnumpy) speed is on par with reikna for both dtypes. So I guess somehow afnumpy's fft is complex128 under the hood...

**Comment by FilipeMaia** [comment]
Could you show me the code for the benchmark? The type of the fft should match the dtype of the array created.

**Comment by ZacDiggum** [comment]
Hm, dtypes do match in the input and output. pure arrayfire is always faster, 3x for complex64 and 1.5x for complex128. I attached the script, you'll see different speedups for different array sizes.
[bench_fft.zip](https://github.com/FilipeMaia/afnumpy/files/178216/bench_fft.zip)

**Comment by FilipeMaia** [comment]
The benchmark is flawed.
For example swapping the order of the tests (testing first arrayfire and then afnumpy) makes arrayfire look slower, but that's because you're letting some initializations cloud in your benchmarks:

``` shell
$ python bench_fft.py
('input dtypes:\t', dtype('complex64'), <Dtype.c32: 1>)
('t_af:', 0.002671778917312622)
('t_afnp:', 0.0022345280647277834)
('output dtypes:\t', dtype('complex64'), <Dtype.c32: 1>, '\n')
('input dtypes:\t', dtype('complex128'), <Dtype.c64: 3>)
('t_af:', 0.007389683961868286)
('t_afnp:', 0.007509784936904907)
('output dtypes:\t', dtype('complex128'), <Dtype.c64: 3>, '\n')
```

The performance should be very similar, with a small overhead for afnumpy (it can't be any faster than arrayfire as it just calls arrayfire).

BTW the above benchmark was with 1000 iterations. If you only do 100 the effect is even worse:

``` shell
$ python bench_fft.py
('input dtypes:\t', dtype('complex64'), <Dtype.c32: 1>)
('t_af:', 0.007282390594482422)
('t_afnp:', 0.002245910167694092)
('output dtypes:\t', dtype('complex64'), <Dtype.c32: 1>, '\n')
('input dtypes:\t', dtype('complex128'), <Dtype.c64: 3>)
('t_af:', 0.007400569915771485)
('t_afnp:', 0.007512679100036621)
('output dtypes:\t', dtype('complex128'), <Dtype.c64: 3>, '\n')
```

**Comment by FilipeMaia** [comment]
The following benchmark corrects the problem with the initialization and gives more accurate results:

``` python
import numpy as np, afnumpy as afnp
from afnumpy import fft as afft
import arrayfire as af
from time import time

# afnumpy ffts
def fft_af(inp):
    out = af.fft2(inp); af.device.sync()
    return out

# af ffts
def fft_afnp(inp):
    out = afft.fft2(inp); af.device.sync()
    return out

n = 2048    # input arrays are n*n
k = 100 # iterations
mydtypes = [np.complex64, np.complex128]

for mydtype in mydtypes:
    x_h = (np.random.rand(n,n)*(1.+1.j)).astype(mydtype)
    x_afnp = afnp.array(x_h, dtype=mydtype)
    x_af = af.np_to_af_array(x_h.astype(mydtype))

    print( 'input dtypes:\t', x_afnp.dtype, x_af.dtype())
    ########################################################
    # The following line takes care of the initializations #
    ########################################################
    y_af = fft_af(x_af)

    t0 = time()
    for i in range(k):
        y_af = fft_af(x_af)
    t_af = (time()-t0)/k
    print( 't_af:',t_af )

    t0 = time()
    for i in range(k):
        y_afnp = fft_afnp(x_afnp)
    t_afn = (time()-t0)/k
    print( 't_afnp:',t_afn )

    print( 'output dtypes:\t', y_afnp.dtype, y_af.dtype(), '\n')
```

``` shell
$ python bench_fft.py
('input dtypes:\t', dtype('complex64'), <Dtype.c32: 1>)
('t_af:', 0.002205629348754883)
('t_afnp:', 0.00224276065826416)
('output dtypes:\t', dtype('complex64'), <Dtype.c32: 1>, '\n')
('input dtypes:\t', dtype('complex128'), <Dtype.c64: 3>)
('t_af:', 0.007388050556182861)
('t_afnp:', 0.007507190704345703)
('output dtypes:\t', dtype('complex128'), <Dtype.c64: 3>, '\n')
```

If you still have problems let me know and I reopen the issue.
