### ISSUE TITLE
definition of `dot`

### ISSUE THREAD

**Issue by billpage** [FilipeMaia/afnumpy#24]
https://github.com/FilipeMaia/afnumpy/blob/master/afnumpy/linalg/linalg.py#L14

As implemented, `afnumpy.dot` differs from the standard **numpy** definition

http://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html#numpy.dot

is this intentional?

**Comment by FilipeMaia** [comment]
It's certainly not intentional. 
What happened was that only the current functionality was requested and so that implemented. If you need the rest I can look into implementing it. 
Or if you wish to submit a pull request to implement it that would be even better :wink:.

**Comment by billpage** [comment]
Thanks. I'll do that and probably a bit more. There still seems to be quite a bit missing if the target is that this package should be a "drop-in" replacement for numpy.  But what I have seen so far looks great.  Is there a possibility that `afnumpy` could become part of the ArrayFire distribution? Note: I am also using and comparing `gnumpy` based on `CUDAmat`. I'd be glad to discuss this further.

**Comment by FilipeMaia** [comment]
There definitely is a _lot_ missing. I started afnumpy as I needed a quick and easy way to do some simple calculations with the GPU, so I did what I required first. But it should be relatively straightforward to implement many other functions, specially those that ArrayFire already does. I don't think ArrayFire is interested in including afnumpy but maybe @pavanky can chime in.

**Comment by FilipeMaia** [comment]
BTW about `gnumpy`, I don't know much about it, but I was attracted to ArrayFire because of its ability to run on a variety of hardware.
