### ISSUE TITLE
pandas?

### ISSUE THREAD

**Issue by KiaraGrouwstra** [FilipeMaia/afnumpy#25]
Hi,
Seeing this library made me wonder if anyone had tried using this as a `numpy` drop-in for `pandas`. If it works, I'd wonder why this isn't common practice yet (-> single-digit github stars), cuz it sounds pretty cool! :)

**Comment by FilipeMaia** [comment]
Hi,
Currently `afnumpy` is missing many `numpy` functions, so this will not yet work. But the goal is to have all the functions. Also I don't know if `pandas` uses the C api of numpy, which `afnumpy` does not implement.
