### ISSUE TITLE
Supported Python version?

### ISSUE THREAD

**Issue by ghost** [FilipeMaia/afnumpy#26]
Latest updates on PyPI say 2016, but there are examples that still use print-statement. Setup.py doesn't contain Python-version metadata. I'd love to know if this is supported in recent versions of Python, that would make it a great tool for teaching ML according to the [mostly numpy-based examples](http://neuralnetworksanddeeplearning.com/) in many Deep Learning books.

**Comment by FilipeMaia** [comment]
The examples were only run with Python 2 but the code works with both Python 2 or 3. The bigger issue is lack of implemented functions. We've been adding functions as we need them and this is often quite easy to do.
If you have an application which requires certain functions, just create an issue and they might get implemented soon.

**Comment by ghost** [comment]
Great news, thank you - I don't think even ML-on-numpy uses many features outside basic matrix multiplications, etcetera, so that's perfect for my use-case anyway.
