### ISSUE TITLE
Slicing a multidimensional array

### ISSUE THREAD

**Issue by daurer** [FilipeMaia/afnumpy#3]
When slicing a multidimensional array like this:

``` python
a = afnumpy.ones((10,20))
print a[0]
print a[0,:]
```

```
array([ 1.])
array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.])
```

wouldn't it be better if the first case would match the second case, always slicing the remaining dimensions rather than selecting the first item along all dimensions?

**Comment by FilipeMaia** [comment]
Yes, that's a bug (as it doesn't match what numpy does).
I'll see what I can do to fix it.

**Comment by FilipeMaia** [comment]
This should be fixed by now.
