### ISSUE TITLE
Use arrayfire function

### ISSUE THREAD

**Issue by huibinchang** [FilipeMaia/afnumpy#30]
Hi, Filipe.  I want to know how to use the arrayfire function as arrayfire.matmul for matrix multiplication and other functions in arrayfire.linalg. Does it exist a easy way for this? 
I tried to use af.arrayfire.matmul. However, it failed since it can not recognize the data type. To run the code, I have to copy the data from GPU to CPU, and then use numpy function instead of afnumpy.

Thanks.

**Comment by FilipeMaia** [comment]
Hi,

This is kinda of a hack but you can do it like this:
```python
a = afnumpy.ones((3,3))
b = afnumpy.array(afnumpy.arrayfire.matmul(a.d_array, a.d_array))
```

**Comment by huibinchang** [comment]
Thanks for your quick response. I will have a try! 

By the way, afnumpy is really efficient for me (Only use Matlab before). 


Huibin

**Comment by FilipeMaia** [comment]
Thanks!

**Comment by FilipeMaia** [comment]
BTW in the latest afnumpy `afnumpy.dot` does matrix multiplication when given 2D arrays as input, just like regular numpy.

**Comment by huibinchang** [comment]
Sounds great! I will have a try!



Huibin

////////////////////////////////////
常慧宾
数学科学学院
天津师范大学

CHANG Huibin,
School of Mathematical Sciences,
Tianjin Normal University,
P.R. China

2018-06-01 12:46 GMT-07:00 Filipe Maia <notifications@github.com>:
