### ISSUE TITLE
arrayfire to afnumpy array

### ISSUE THREAD

**Issue by huibinchang** [FilipeMaia/afnumpy#31]
Hi,  Filipe. Now I tried to use arrayfire function so that I needed to create array A in arrayfire and then change the type to afnumpy array by Aaf=afnumpy.array(A). However, it was very slow. I am wondering why it is so slow (both are in GPU). Or can you tell me how to make it faster?

Thanks.

Huibin

**Comment by FilipeMaia** [comment]
Can you show an example?

**Comment by huibinchang** [comment]
import afnumpy as af
import arrayfire
L=af.ones((256*256,10));
R=af.ones((10,2000));
M=arrayfire.blas.matmulTT(L.d_array,R.d_array)
Maf=af.array(M)


Thanks.

**Comment by huibinchang** [comment]
I saw this example you posted before.
----------------------------------------------------------------------------------------
import arrayfire as af
import afnumpy as afnp
a = af.randu(3,2)
shape = a.dims()[::-1]
c = afnp.ndarray(shape, dtype='f', buffer=a.raw_ptr(), buffer_type=af.get_active_backend())

========================================================


Why it did not work?  Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __init__() got an unexpected keyword argument 'buffer_type'

**Comment by FilipeMaia** [comment]
With the commits I just pushed I get the following results:

```python
In [1]: import afnumpy as af
   ...: import arrayfire
   ...: L=af.ones((256*256,10));
   ...: R=af.ones((10,2000));
   ...: M=arrayfire.blas.matmulTT(L.d_array,R.d_array)
   ...:

In [2]: %timeit Maf=af.array(M)
The slowest run took 4.59 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 3: 159 µs per loop
```

```python
In [1]: import arrayfire as af

In [2]: import afnumpy as afnp

In [3]: a = af.randu(3,2)

In [4]: shape = a.dims()[::-1]

In [5]: c = afnp.ndarray(shape, dtype='f', buffer=a.raw_ptr(), buffer_type=af.ge
   ...: t_active_backend())

In [6]: c
Out[6]:
array([[ 0.41073772,  0.82237053,  0.95179963],
       [ 0.17936543,  0.41982353,  0.00807349]], dtype=float32)
```

Try to pull and let me know if this fixes your problems.

**Comment by huibinchang** [comment]
It is really fast now. Thanks.

By the way, it seems that af.array(M) return the transpose of M. To make have same dim, I have to use af.transpose(af.array(M))

Huibin

**Comment by FilipeMaia** [comment]
The reason why it looks like it returns the transpose is that arrayfire uses column major format (fortran style), while numpy by default uses row major format. So a (3,2) arrayfire array become a (2,3) afnumpy array, even though they refer to the same data in memory.

**Comment by huibinchang** [comment]
I see. Thanks so much! Thanks for your quick response and great contributions  to make a friendly interface.


Huibin
