### ISSUE TITLE
Segmentation fault 

### ISSUE THREAD

**Issue by daurer** [FilipeMaia/afnumpy#33]
This code example produces a segmentation fault on my GPU:

```python
import afnumpy as af
import afnumpy.fft as fft
a = fft.fftn(af.zeros(100))
```

can you reproduce?

**Comment by FilipeMaia** [comment]
What card do you have and with what backend?
I can't reproduce:
```python
In [11]: import afnumpy as af
    ...: import afnumpy.fft as fft
    ...: a = fft.fftn(af.zeros(100))
    ...:

In [12]: afnumpy.arrayfire.get_active_backend()
Out[12]: 'opencl'
```

**Comment by daurer** [comment]
I am using the 'cuda' backend (on GTX 108)

```python
In [1]: import afnumpy as af

In [2]: af.arrayfire.get_active_backend()
Out[2]: 'cuda'
```

**Comment by daurer** [comment]
Also get a segfault for this example:

```python
import afnumpy as af
a = af.random.random((3,3,3))+af.random.random((3,3,3))*1.0j
b = af.dot(a,a))
```

**Comment by FilipeMaia** [comment]
I would guess there's something seriously wrong with arrayfire itself.
Could you try running the equivalent arrayfire operations directly?
```python
import arrayfire
a = arrayfire.randu(100)
b = arrayfire.fft(a)
```

**Comment by daurer** [comment]
Thanks for the hint. You were right, same thing happens for the arrayfire example. And as for the previous examples, the segfaults happens when terminating the python process. (will close the issue because it seems not related to afnumpy)
