### ISSUE TITLE
module 'afnumpy' has no attribute 'pad'

### ISSUE THREAD

**Issue by smarkesini** [FilipeMaia/afnumpy#36]
It would be great to have some of the functionality of numpy.pad

I am trying to do something like this:
import afnumpy as xp
num_rays=64
num_slices=64
true_obj=xp.ones((num_slices,num_rays,num_rays),dtype='float32')
pad_1D        = num_rays//2
padding_array = ((0, 0), (pad_1D, pad_1D), (pad_1D, pad_1D))
true_obj = xp.pad(true_obj, padding_array, 'constant', constant_values = 0)

**Comment by FilipeMaia** [comment]
Hi Stefano!

I'll look into it.
Meanwhile, for code sections which are not performance sensitive the following workaround should work:
```python
import afnumpy as xp
import afnumpy as np
num_rays=64
num_slices=64
true_obj=xp.ones((num_slices,num_rays,num_rays),dtype='float32')
pad_1D = num_rays//2
padding_array = ((0, 0), (pad_1D, pad_1D), (pad_1D, pad_1D))
# Convert to numpy for padding
true_obj = xp.array(np.pad(np.array(true_obj), padding_array, 'constant', constant_values = 0))
```
