### ISSUE TITLE
How to convert  afnumpy array to arrayfire array?

### ISSUE THREAD

**Issue by 3togo** [FilipeMaia/afnumpy#38]
How to convert  afnumpy array to arrayfire array?

**Comment by 3togo** [comment]
I could do it by first converting afnumpy array to python list. However, is there any better way? 
arrayfire.Array(list(afnumpy_arr), shape)

**Comment by 3togo** [comment]
should use af.cast

 af.cast(a.d_array, a.d_array.dtype())

**Comment by FilipeMaia** [comment]
Sorry I couldn't answer earlier. 
Glad you figured out the solution.
If you're using the CUDA backend I suggest you look into cupy.
