### ISSUE TITLE
Slicing with a boolean spanning only a few dimensions

### ISSUE THREAD

**Issue by ekeberg** [FilipeMaia/afnumpy#8]
The following code works using numpy but on afnumpy it crashes with the message "Size mismatch between input and output". If mask has the same dimension as a it works fine.

a = afnumpy.ones((5, 3), dtype="float32")
mask = afnumpy.arange(5) > 2
a[mask, :] = 0.

**Comment by FilipeMaia** [comment]
``` python
a = afnumpy.ones((5, 3), dtype="float32")
mask = afnumpy.arange(5) > 2
a[mask, :]
```

works, but the `__setitem__()` still does not.

The following also does not work:

``` python
import afnumpy

a = afnumpy.ones((5, 3, 2), dtype="float32")
mask = afnumpy.random.random((5, 3)) > 0.5
a[mask, :]
```

**Comment by FilipeMaia** [comment]
The `__setitem__()` problem comes from arrayfire/arrayfire-python#42

**Comment by FilipeMaia** [comment]
`__setitem__()` with booleans now works, since arrayfire-python was just fixed, but there are still problems with multidimensional boolean arrays.

**Comment by FilipeMaia** [comment]
This seems to be fixed now.
